//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngo
    {
        public int id { get; set; }
        public Nullable<int> resid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<System.DateTime> placingdate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
    }
}
