//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public int id { get; set; }
        public string resname { get; set; }
        public string food { get; set; }
        public string quantity { get; set; }
        public string available { get; set; }
    }
}
